# Generated by Django 4.2.10 on 2026-06-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_platform_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='experiment',
            new_name='playground__user_id_c14e30_idx',
            old_name='playground__user_id_created_idx',
        ),
    ]
