# Generated by Django 6.0 on 2026-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('submission', 'Submission'), ('submission_success', 'Submission Success'), ('submission_fail', 'Submission Failed'), ('video_completed', 'Video Completed'), ('mentor_used', 'Mentor Used'), ('problem_solved', 'Problem Solved'), ('course_purchased', 'Course Purchased')], db_index=True, max_length=30)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('score_delta', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('problems_attempted', models.IntegerField(default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('streak_day', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
