# Generated by Django 6.0 on 2026-02-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', '-created_at'], name='timeline_ac_user_id_c79701_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='timeline_ac_user_id_530a84_idx'),
        ),
        migrations.AddIndex(
            model_name='performancesnapshot',
            index=models.Index(fields=['user', '-date'], name='timeline_pe_user_id_09634f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancesnapshot',
            unique_together={('user', 'date')},
        ),
    ]
