# Generated by Django 6.0 on 2026-02-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentormessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mentor.mentorsession'),
        ),
        migrations.AddIndex(
            model_name='mentorsession',
            index=models.Index(fields=['user', '-last_active_at'], name='mentor_ment_user_id_7c98b2_idx'),
        ),
        migrations.AddIndex(
            model_name='mentormessage',
            index=models.Index(fields=['session', 'created_at'], name='mentor_ment_session_a5c085_idx'),
        ),
        migrations.AddIndex(
            model_name='mentormessage',
            index=models.Index(fields=['session', 'role', 'created_at'], name='mentor_ment_session_2330f4_idx'),
        ),
    ]
