# Generated by Django 4.2.10 on 2026-06-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_lesson_ids', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('is_adaptive', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('overall_mastery', models.FloatField(default=0.0)),
                ('avg_session_duration_minutes', models.FloatField(default=0.0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_problems_solved', models.IntegerField(default=0)),
                ('total_quizzes_passed', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('frustration_score', models.FloatField(default=0.0)),
                ('dropout_risk', models.FloatField(default=0.0)),
                ('preferred_content_type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('coding', 'Coding'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('preferred_difficulty', models.CharField(default='beginner', max_length=20)),
                ('weak_concepts', models.JSONField(default=list)),
                ('strong_concepts', models.JSONField(default=list)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_tag', models.CharField(choices=[('python_ml', 'Python for ML'), ('numpy_pandas', 'NumPy & Pandas'), ('statistics', 'Statistics'), ('linear_algebra', 'Linear Algebra'), ('regression', 'Regression'), ('classification', 'Classification'), ('evaluation_metrics', 'Evaluation Metrics'), ('feature_engineering', 'Feature Engineering'), ('gradient_descent', 'Gradient Descent'), ('regularization', 'Regularization'), ('ensemble_learning', 'Ensemble Learning'), ('svm', 'SVM'), ('clustering', 'Clustering'), ('pca', 'PCA & Dimensionality Reduction'), ('neural_networks', 'Neural Networks'), ('cnn', 'Convolutional Neural Networks'), ('rnn', 'Recurrent Neural Networks'), ('transformers', 'Transformers'), ('backpropagation', 'Backpropagation'), ('model_deployment', 'Model Deployment'), ('mlops', 'MLOps')], db_index=True, max_length=50)),
                ('quiz_mastery', models.FloatField(default=0.0)),
                ('coding_mastery', models.FloatField(default=0.0)),
                ('video_completion_rate', models.FloatField(default=0.0)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('coding_attempts', models.IntegerField(default=0)),
                ('is_struggling', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mastery_score'], name='learner_con_user_id_6333c0_idx')],
                'unique_together': {('user', 'concept_tag')},
            },
        ),
    ]
