# Generated by Django 6.0.2 on 2026-08-25 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learner", "0002_profile_bkt_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptmastery",
            name="gap_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="conceptmastery",
            index=models.Index(
                fields=["user", "concept_tag", "mastery_score"],
                name="learner_con_user_id_7553e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptmastery",
            index=models.Index(
                fields=["user", "gap_detected"], name="learner_con_user_id_b3baea_idx"
            ),
        ),
    ]
