# Generated by Django 6.0 on 2026-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(db_index=True, default=0)),
                ('problems_solved', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('streak_days', models.IntegerField(default=0)),
                ('rank', models.IntegerField(db_index=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_points', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('submission_success', 'Submission Success'), ('submission_fail', 'Submission Failed'), ('streak_bonus', 'Streak Bonus'), ('problem_solved', 'Problem Solved')], max_length=30)),
                ('points_delta', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
