# Generated by Django 6.0 on 2026-02-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboardevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['-total_points', 'updated_at'], name='leaderboard_total_p_dd4eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['user', '-total_points'], name='leaderboard_user_id_2392f5_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardevent',
            index=models.Index(fields=['user', '-created_at'], name='leaderboard_user_id_9d7da2_idx'),
        ),
    ]
