# Generated by Django 6.0 on 2026-03-26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('period', models.CharField(choices=[('alltime', 'All Time'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=20)),
                ('snapshot_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date', 'rank'],
                'unique_together': {('user', 'period', 'snapshot_date')},
            },
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['period', 'snapshot_date', 'rank'], name='leaderboard_period_0ac0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['user', 'period', 'snapshot_date'], name='leaderboard_user_id_9cc0c2_idx'),
        ),
    ]
