# Generated by Django 6.0.2 on 2026-03-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_leaderboardsnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaderboardsnapshot',
            new_name='leaderboard_period_d008c8_idx',
            old_name='leaderboard_period_0ac0cf_idx',
        ),
        migrations.RenameIndex(
            model_name='leaderboardsnapshot',
            new_name='leaderboard_user_id_f3d6c4_idx',
            old_name='leaderboard_user_id_9cc0c2_idx',
        ),
    ]
