# Generated by Django 6.0 on 2026-02-12 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/%Y/%m/')),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learn_invoices',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('video_type', models.CharField(choices=[('YOUTUBE', 'YouTube'), ('UPLOAD', 'Uploaded Video')], default='YOUTUBE', help_text='Type of video: YouTube or uploaded', max_length=20)),
                ('youtube_id', models.CharField(blank=True, help_text='ONLY the YouTube video ID (not full URL). Extracted server-side.', max_length=32)),
                ('video_url', models.URLField(blank=True, help_text='DEPRECATED: Use youtube_id for YouTube videos. Kept for backward compatibility.', max_length=500)),
                ('duration_minutes', models.IntegerField()),
                ('is_preview', models.BooleanField(default=False, help_text='Preview lessons are accessible without payment')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learn_lessons',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('last_position_seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'learn_lesson_progress',
                'ordering': ['-last_watched_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('stripe_client_secret', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learn_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, help_text='Course cover image URL', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('duration_hours', models.IntegerField(help_text='Estimated course duration in hours')),
                ('is_paid', models.BooleanField(default=False, help_text='True if course requires payment')),
                ('is_free', models.BooleanField(default=True, help_text='True if course is free (backward compatibility)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in currency units (null for free courses)', max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cover_image', models.URLField(blank=True, help_text='Course cover image URL (alias for thumbnail)', max_length=500)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learn_courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='learn_cours_is_publ_187d39_idx'), models.Index(fields=['is_free'], name='learn_cours_is_free_a65e44_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learn.course')),
            ],
            options={
                'db_table': 'learn_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
