# Generated by Django 6.0.2 on 2026-02-18 18:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_alter_course_id_alter_enrollment_id_alter_lesson_id_and_more'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(db_index=True, help_text='Short unique ID for verification (e.g., CERT-XXXX-XXXX)', max_length=32, unique=True)),
                ('user_name', models.CharField(help_text="User's name at time of issue", max_length=255)),
                ('course_title', models.CharField(help_text='Course title at time of issue', max_length=255)),
                ('course_level', models.CharField(max_length=20)),
                ('completion_date', models.DateField()),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/%Y/%m/')),
                ('verification_url', models.URLField(blank=True, max_length=500)),
                ('qr_code_url', models.URLField(blank=True, max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'learn_certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('enrollments', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_watch_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lesson_completions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'learn_course_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learn_course_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('average_watch_time_seconds', models.IntegerField(default=0)),
                ('drop_off_count', models.IntegerField(default=0, help_text='Users who stopped at this lesson')),
            ],
            options={
                'db_table': 'learn_lesson_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='learn_cours_is_free_a65e44_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='learn_enrol_stripe__130fb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='learn_lesso_enrollm_13d18e_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='completion_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of students who completed', max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Estimated total duration in hours', max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_avatar',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, help_text='Brief instructor bio'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='Primary instructor name', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], db_index=True, default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite knowledge/skills'),
        ),
        migrations.AddField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average course rating (0-5)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_rating',
            field=models.IntegerField(blank=True, default=None, help_text='Minimum user rating required to enroll (null = no requirement)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief 1-2 sentence summary for cards', max_length=300),
        ),
        migrations.AddField(
            model_name='course',
            name='students_count',
            field=models.IntegerField(default=0, help_text='Number of enrolled students'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Course tags for search'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text='Who this course is for'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration_minutes',
            field=models.IntegerField(default=0, help_text='Cached total duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(default=0, help_text='Cached lesson count'),
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(blank=True, help_text='Optional track this course belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='tracks.track'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_youll_learn',
            field=models.JSONField(blank=True, default=list, help_text='Learning outcomes'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True if payment was made'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe payment intent ID or other reference', max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hosted_video_key',
            field=models.CharField(blank=True, help_text='S3 object key for signed URL generation', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='hosted_video_url',
            field=models.URLField(blank=True, help_text='Hosted video URL (S3/CDN - DO NOT expose directly)', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes',
            field=models.TextField(blank=True, help_text='Markdown lesson notes'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='List of resources [{name, url, type}]'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (for free courses)', max_length=500),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='first_watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(db_index=True, default=True, help_text='True if course is free'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='True if course requires payment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in currency units (null for free courses)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(db_index=True, default=False, help_text='Preview lessons accessible without enrollment'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('hosted', 'Hosted/CDN Video')], default='youtube', help_text='Video source type', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube video ID extracted from URL', max_length=32),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learn.enrollment'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='last_position_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_free', 'level'], name='learn_cours_is_free_7745aa_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['track', 'level'], name='learn_cours_track_i_219a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['required_rating'], name='learn_cours_require_302664_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-students_count'], name='learn_cours_student_829b81_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-rating_average'], name='learn_cours_rating__2810d9_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='learn_enrol_course__ee20dc_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['payment_reference'], name='learn_enrol_payment_3afa30_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['-last_accessed_at'], name='learn_enrol_last_ac_6c14bf_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_preview'], name='learn_lesso_is_prev_c58fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='learn_lesso_enrollm_26b346_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'is_completed'], name='learn_lesso_lesson__b5c27f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='learn_payme_stripe__a03d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_checkout_session_id'], name='learn_payme_stripe__7a0a13_idx'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='learn.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='learn.enrollment'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseanalytics',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='learn.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='learn.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='learn.enrollment'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonanalytics',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='learn.lesson'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='progress_percentage',
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_id'], name='learn_certi_certifi_47ebe6_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['user', '-issued_at'], name='learn_certi_user_id_4f8013_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='courseanalytics',
            index=models.Index(fields=['course', '-date'], name='learn_cours_course__52dbe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseanalytics',
            unique_together={('course', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lessonanalytics',
            unique_together={('lesson', 'date')},
        ),
    ]
