# Generated by Django 4.2.10 on 2026-02-23 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0005_certificate_courseanalytics_courserating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Quiz title (auto-generated)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Quiz description')),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum percentage to pass (0-100)')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Time limit in seconds (null = no limit)', null=True)),
                ('generated_by', models.CharField(choices=[('gemini', 'Generated by Gemini'), ('manual', 'Manually Created')], default='gemini', max_length=20)),
                ('generation_prompt', models.TextField(blank=True, help_text='Prompt used for Gemini generation')),
                ('source_transcript', models.TextField(blank=True, help_text='Lesson transcript used for generation')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(help_text='Each lesson has exactly one quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learn.lesson')),
            ],
            options={
                'db_table': 'learn_quizzes',
                'ordering': ['lesson__course', 'lesson__order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict, help_text="User answers: {question_id: 'A'|'B'|'C'|'D'}")),
                ('score', models.PositiveIntegerField(default=0, help_text='Score as percentage (0-100)')),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='learn.enrollment')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn_quiz_attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'quiz'], name='learn_quiz__user_id_a0b706_idx'), models.Index(fields=['quiz', 'passed'], name='learn_quiz__quiz_id_d9a12a_idx'), models.Index(fields=['user', '-started_at'], name='learn_quiz__user_id_6ab294_idx')],
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The question text')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('option_a', models.TextField(help_text='Option A text')),
                ('option_b', models.TextField(help_text='Option B text')),
                ('option_c', models.TextField(help_text='Option C text')),
                ('option_d', models.TextField(help_text='Option D text')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Correct answer (A/B/C/D)', max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after answering')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('topic', models.CharField(blank=True, help_text='Topic tag', max_length=100)),
                ('times_answered', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learn.quiz')),
            ],
            options={
                'db_table': 'learn_mcqs',
                'ordering': ['quiz', 'order'],
                'indexes': [models.Index(fields=['quiz', 'order'], name='learn_mcqs_quiz_id_47c622_idx')],
            },
        ),
    ]
