# Generated by Django 4.2.10 on 2026-02-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0006_quiz_quizattempt_mcq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Quiz title (auto-generated)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Quiz description')),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('passing_score', models.PositiveIntegerField(default=75, help_text='Minimum percentage to pass (0-100)')),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Time limit in seconds (null = no limit)', null=True)),
                ('generated_by', models.CharField(choices=[('gemini', 'Generated by Gemini'), ('manual', 'Manually Created')], default='gemini', max_length=20)),
                ('generation_prompt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(help_text='Each course has one final quiz', on_delete=django.db.models.deletion.CASCADE, related_name='final_quiz', to='learn.course')),
            ],
            options={
                'db_table': 'learn_course_quizzes',
                'ordering': ['course__title'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('course_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learn.coursequiz')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz_attempts', to='learn.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learn_course_quiz_attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'course_quiz'], name='learn_cours_user_id_1989b0_idx'), models.Index(fields=['course_quiz', 'passed'], name='learn_cours_course__5ae877_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseMCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(help_text='The question text')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('option_a', models.TextField(help_text='Option A text')),
                ('option_b', models.TextField(help_text='Option B text')),
                ('option_c', models.TextField(help_text='Option C text')),
                ('option_d', models.TextField(help_text='Option D text')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Correct answer (A/B/C/D)', max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('times_answered', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learn.coursequiz')),
                ('source_lesson', models.ForeignKey(blank=True, help_text='Lesson this question is derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_mcqs', to='learn.lesson')),
            ],
            options={
                'db_table': 'learn_course_mcqs',
                'ordering': ['course_quiz', 'order'],
                'indexes': [models.Index(fields=['course_quiz', 'order'], name='learn_cours_course__aaec8e_idx')],
            },
        ),
    ]
