# Generated by Django 6.0.2 on 2026-03-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_add_course_final_quiz_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='learn_invoi_user_id_6237d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='learn_invoi_invoice_eacbbd_idx',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
