# Generated by Django 4.2.10 on 2026-06-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_remove_invoice_learn_invoi_user_id_6237d6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'learn_modules',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='concept_tag',
            field=models.CharField(blank=True, db_index=True, help_text='ML concept tag for mastery tracking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Lesson difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this lesson available for enrollment'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives for this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Lessons that must be completed first', related_name='unlocks', to='learn.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Additional tags for lesson categorization'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='concept_tag',
            field=models.CharField(blank=True, db_index=True, help_text='ML concept tag for mastery tracking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(default='beginner', help_text='Quiz difficulty level', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module this lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='learn.module'),
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('concept_tag', models.CharField(blank=True, db_index=True, help_text='ML concept tag for mastery tracking', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_concepts', models.JSONField(default=list, help_text='List of expected concepts for this problem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='learn.lesson')),
            ],
            options={
                'db_table': 'learn_coding_problems',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['concept_tag', 'difficulty'], name='learn_codin_concept_0a2694_idx')],
            },
        ),
    ]
