# Generated by Django 4.2.10 on 2026-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_platform_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingproblem',
            name='expected_concepts',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['slug'], name='learn_codin_slug_91b47f_idx'),
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['is_active', 'difficulty'], name='learn_codin_is_acti_26a42d_idx'),
        ),
    ]
