# Generated by Django 4.2.10 on 2026-03-30 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=32)),
                ('avg_score', models.FloatField(default=0.0)),
                ('total_runs', models.IntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('preferred_models', models.JSONField(blank=True, default=list)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_user_profile',
                'indexes': [models.Index(fields=['skill_level'], name='intelligenc_skill_l_063205_idx'), models.Index(fields=['-last_active'], name='intelligenc_last_ac_a2dbb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('problem', 'Problem'), ('playground', 'Playground'), ('mentor', 'Mentor'), ('learn', 'Learn')], max_length=32)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_93344f_idx'), models.Index(fields=['user', 'activity_type', '-created_at'], name='intelligenc_user_id_8ebc2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_suggestion_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_7e4569_idx'), models.Index(fields=['user', 'suggestion_type', '-created_at'], name='intelligenc_user_id_ea1393_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('model_type', models.CharField(max_length=128)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('task_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_experiment_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intelligence_experiment_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='intelligenc_user_id_11e642_idx'), models.Index(fields=['user', 'model_type'], name='intelligenc_user_id_84aa63_idx'), models.Index(fields=['user', 'dataset_name'], name='intelligenc_user_id_033a60_idx')],
            },
        ),
    ]
