# Generated by Django 4.2.10 on 2026-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contests_participated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='problems_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
    ]
