# Generated by Django 4.2.10 on 2026-03-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_contests_participated_user_problems_solved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contests_participated',
        ),
    ]
