# Generated by Django 4.2.10 on 2026-03-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_tagline_user_twitter_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=39),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['github_username'], name='users_github__5cee41_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['linkedin_id'], name='users_linkedi_67db2f_idx'),
        ),
    ]
