# Generated by Django 6.0 on 2026-02-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='discussions.category'),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='discussions.thread'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', '-last_post_at'], name='discussions_categor_40ceff_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['created_by', '-created_at'], name='discussions_created_f41ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-last_post_at'], name='discussions_last_po_b27e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'created_at'], name='discussions_thread__606473_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_by', '-created_at'], name='discussions_created_906713_idx'),
        ),
    ]
