# Generated by Django 6.0 on 2026-02-12 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('problem_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('metric', models.CharField(choices=[('accuracy', 'Accuracy'), ('f1', 'F1 Score'), ('rmse', 'RMSE')], max_length=20)),
                ('target_column', models.CharField(max_length=100)),
                ('dataset_dir', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_problems',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_tests', models.JSONField(blank=True, default=list, help_text='Dataset splits for public evaluation')),
                ('private_tests', models.JSONField(blank=True, default=list, help_text='Dataset splits for private submission evaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Suite',
                'verbose_name_plural': 'Test Suites',
                'db_table': 'ml_testsuites',
            },
        ),
        migrations.CreateModel(
            name='DatasetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loader_type', models.CharField(choices=[('sklearn', 'scikit-learn built-in dataset'), ('csv', 'CSV file on disk')], help_text='Type of data loader: sklearn built-in or CSV file', max_length=20)),
                ('dataset_identifier', models.CharField(help_text="For sklearn: 'iris', 'breast_cancer', 'digits', 'wine'. For CSV: path to file.", max_length=255)),
                ('test_size', models.FloatField(default=0.2, help_text='Fraction of data for testing (0.0-1.0)')),
                ('random_state', models.IntegerField(default=42, help_text='Random seed for reproducible train/test split')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_config', to='ml.problem')),
            ],
            options={
                'verbose_name': 'Dataset Configuration',
                'verbose_name_plural': 'Dataset Configurations',
                'db_table': 'ml_datasetconfigs',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Full code snapshot as submitted by user')),
                ('metric', models.CharField(help_text='Metric used for evaluation (accuracy, f1, rmse, etc)', max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='Score on metric (0.0-1.0 for accuracy, varies for others)')),
                ('threshold', models.FloatField(default=0.0, help_text='Submission threshold value at time of submission')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], help_text='ACCEPTED=meets threshold, REJECTED=below threshold, ERROR=eval error', max_length=20)),
                ('rank', models.IntegerField(blank=True, help_text='Leaderboard rank (only for ACCEPTED submissions)', null=True)),
                ('error_log', models.TextField(blank=True, help_text='Error message if status=ERROR', null=True)),
                ('reason', models.TextField(blank=True, help_text="Reason for rejection if status=REJECTED (e.g., 'Score 0.63 below threshold 0.80')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('runtime_seconds', models.FloatField(blank=True, null=True)),
                ('test_results', models.JSONField(blank=True, default=list, help_text='Detailed evaluation results (optional)')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ml.problem')),
            ],
            options={
                'db_table': 'ml_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
