# Generated by Django 4.2.10 on 2026-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_alter_datasetconfig_id_alter_problem_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['difficulty_rating', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='ml_submissi_problem_2f878b_idx',
        ),
        migrations.AddField(
            model_name='problem',
            name='dataset_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dataset metadata: shape, features, target distribution, etc.'),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty_rating',
            field=models.IntegerField(choices=[(800, 'Easy (800)'), (1200, 'Medium (1200)'), (1600, 'Hard (1600)'), (2000, 'Expert (2000)')], default=800, help_text='Problem difficulty rating (800=Easy, 1200=Medium, 1600=Hard, 2000=Expert)'),
        ),
        migrations.AddField(
            model_name='problem',
            name='evaluation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Evaluation configuration: test splits, cross-validation settings, etc.'),
        ),
        migrations.AddField(
            model_name='problem',
            name='hidden_dataset_location',
            field=models.CharField(blank=True, help_text='S3 path or secure location for hidden evaluation dataset', max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='industrial_constraints',
            field=models.TextField(blank=True, help_text="Industrial constraints and requirements (e.g., 'Model must be < 10MB', 'Latency < 100ms')"),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_competition_problem',
            field=models.BooleanField(default=False, help_text='True if this problem is part of a competition'),
        ),
        migrations.AddField(
            model_name='problem',
            name='latency_limit_ms',
            field=models.FloatField(blank=True, help_text='Maximum allowed inference latency in milliseconds (null = no limit)', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.FloatField(blank=True, help_text='Maximum allowed memory usage in MB (null = no limit)', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='metric_type',
            field=models.CharField(choices=[('accuracy', 'Accuracy'), ('f1', 'F1 Score'), ('rmse', 'RMSE'), ('mae', 'Mean Absolute Error'), ('r2', 'R² Score'), ('precision', 'Precision'), ('recall', 'Recall'), ('roc_auc', 'ROC AUC')], default='accuracy', help_text='Primary metric for evaluation', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='threshold',
            field=models.FloatField(blank=True, help_text='Minimum score threshold for acceptance (null = no threshold)', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='evaluation_version',
            field=models.CharField(default='1.0.0', help_text='Version of evaluation engine used (for reproducibility)', max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='latency_ms',
            field=models.FloatField(blank=True, help_text='Inference latency in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='meets_threshold',
            field=models.BooleanField(default=False, help_text='Whether submission meets the threshold requirement'),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_mb',
            field=models.FloatField(blank=True, help_text='Memory usage in megabytes', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='model_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Model metadata: type, hyperparameters, feature count, etc.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], help_text='Final verdict: ACCEPTED or REJECTED', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='dataset_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='metric',
            field=models.CharField(blank=True, choices=[('accuracy', 'Accuracy'), ('f1', 'F1 Score'), ('rmse', 'RMSE'), ('mae', 'Mean Absolute Error'), ('r2', 'R² Score'), ('precision', 'Precision'), ('recall', 'Recall'), ('roc_auc', 'ROC AUC')], default='accuracy', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='target_column',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='metric',
            field=models.CharField(help_text='Metric used for evaluation (accuracy, f1, rmse, etc)', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='threshold',
            field=models.FloatField(blank=True, help_text='Submission threshold value at time of submission', null=True),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty_rating', 'is_active'], name='ml_problems_difficu_222f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_competition_problem', 'is_active'], name='ml_problems_is_comp_1928b1_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['slug'], name='ml_problems_slug_9d0563_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status', '-score', 'latency_ms'], name='ml_submissi_problem_2bcb83_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status', '-score', 'latency_ms', 'created_at'], name='ml_submissi_problem_814743_idx'),
        ),
    ]
