# Generated by Django 4.2.10 on 2026-02-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_add_dataset_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='medium', help_text='Problem difficulty: easy, medium, hard, expert', max_length=20),
        ),
    ]
