# Generated by Django 4.2.10 on 2026-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit_mb',
            field=models.IntegerField(default=512, help_text='Maximum allowed memory usage in MB (default: 512)'),
        ),
    ]
