# Generated by Django 4.2.10 on 2026-02-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0009_fix_memory_limit_mb_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_limit_seconds',
            field=models.IntegerField(default=30, help_text='Maximum allowed execution time in seconds (default: 30)'),
        ),
    ]
