# Generated by Django 4.2.10 on 2026-02-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0010_fix_time_limit_seconds_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief 1-2 sentence summary', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(blank=True, help_text='Full problem description (supports markdown)', null=True),
        ),
    ]
