# Generated by Django 4.2.10 on 2026-06-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('VIDEO_STARTED', 'Video Started'), ('VIDEO_COMPLETED', 'Video Completed'), ('VIDEO_SKIPPED', 'Video Skipped'), ('VIDEO_REWATCHED', 'Video Rewatched'), ('LESSON_OPENED', 'Lesson Opened'), ('LESSON_COMPLETED', 'Lesson Completed'), ('QUIZ_STARTED', 'Quiz Started'), ('QUIZ_SUBMITTED', 'Quiz Submitted'), ('QUIZ_PASSED', 'Quiz Passed'), ('QUIZ_FAILED', 'Quiz Failed'), ('CODE_SUBMITTED', 'Code Submitted'), ('CODE_PASSED', 'Code Passed'), ('CODE_FAILED', 'Code Failed'), ('CODE_ERROR', 'Code Error'), ('MENTOR_QUERIED', 'Mentor Queried'), ('SESSION_STARTED', 'Session Started'), ('SESSION_ENDED', 'Session Ended'), ('PLAYGROUND_RUN', 'Playground Run'), ('PROBLEM_OPENED', 'Problem Opened'), ('PROBLEM_SOLVED', 'Problem Solved')], db_index=True, max_length=50)),
                ('content_type', models.CharField(blank=True, choices=[('lesson', 'lesson'), ('quiz', 'quiz'), ('problem', 'problem'), ('video', 'video'), ('playground', 'playground'), ('mentor', 'mentor')], max_length=30, null=True)),
                ('content_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='tracking_le_user_id_2e2ae9_idx'), models.Index(fields=['user', 'content_type', 'content_id'], name='tracking_le_user_id_e1c975_idx'), models.Index(fields=['user', 'timestamp'], name='tracking_le_user_id_e58b3f_idx')],
            },
        ),
    ]
