"""
Extended ML problem registry — 22 additional problems (18 existing + 22 = 40).

Imported into ml.registry to expand PROBLEM_REGISTRY.
"""

import numpy as np
from sklearn.model_selection import train_test_split

from ml.registry import ProblemDefinition


def _generic_classification_loader(n_samples=500, n_features=10, seed=42):
    def loader():
        np.random.seed(seed)
        X = np.random.normal(0, 1, (n_samples, n_features))
        y = (X.sum(axis=1) + np.random.normal(0, 0.3, n_samples) > 0).astype(int)
        meta = {"num_samples": n_samples, "num_features": n_features, "task_type": "classification"}
        return X, y, meta
    return loader


def _generic_regression_loader(n_samples=200, n_features=5, seed=42):
    def loader():
        np.random.seed(seed)
        X = np.random.normal(0, 1, (n_samples, n_features))
        y = X @ np.random.randn(n_features) * 3 + np.random.normal(0, 0.5, n_samples)
        meta = {"num_samples": n_samples, "num_features": n_features, "task_type": "regression"}
        return X, y, meta
    return loader


EXTENDED_PROBLEMS = {
    # Easy (5 new)
    "feature-scaling-pipeline": ProblemDefinition(
        slug="feature-scaling-pipeline",
        title="Feature Scaling Pipeline",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(600, 8, 42),
        description="Build a sklearn Pipeline with scaling achieving >= 0.88 accuracy.",
        difficulty="easy",
        difficulty_rating=800,
        category="fundamentals",
    ),
    "cross-validation-correct": ProblemDefinition(
        slug="cross-validation-correct",
        title="Cross-Validation Without Leakage",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(500, 6, 43),
        description="Implement correct 5-fold CV with Pipeline. Target mean_cv_score >= 0.85.",
        difficulty="easy",
        difficulty_rating=800,
        category="fundamentals",
    ),
    "confusion-matrix-metrics": ProblemDefinition(
        slug="confusion-matrix-metrics",
        title="Confusion Matrix Metrics",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.70,
        dataset_loader=_generic_classification_loader(300, 4, 44),
        description="Compute precision, recall, F1, kappa from confusion matrix.",
        difficulty="easy",
        difficulty_rating=800,
        category="fundamentals",
    ),
    "missing-data-imputation": ProblemDefinition(
        slug="missing-data-imputation",
        title="Missing Data Imputation Strategy",
        task_type="regression",
        default_metric="rmse",
        allowed_metrics=["rmse"],
        submission_threshold=15.0,
        dataset_loader=_generic_regression_loader(300, 6, 45),
        description="Impute MCAR/MAR/MNAR missing values and predict loan_amount.",
        difficulty="easy",
        difficulty_rating=800,
        category="fundamentals",
    ),
    "polynomial-feature-interactions": ProblemDefinition(
        slug="polynomial-feature-interactions",
        title="Polynomial Feature Interactions",
        task_type="regression",
        default_metric="r2",
        allowed_metrics=["r2"],
        submission_threshold=0.70,
        dataset_loader=_generic_regression_loader(250, 3, 46),
        description="Use PolynomialFeatures to achieve R² >= 0.88.",
        difficulty="easy",
        difficulty_rating=800,
        category="fundamentals",
    ),
    # Medium (5 new)
    "credit-risk-calibrated": ProblemDefinition(
        slug="credit-risk-calibrated",
        title="Credit Risk with Probability Calibration",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy", "f1"],
        submission_threshold=0.72,
        dataset_loader=_generic_classification_loader(2000, 10, 101),
        description="CalibratedClassifierCV for loan default probability. Log-loss <= 0.38.",
        difficulty="medium",
        difficulty_rating=1200,
        category="finance",
    ),
    "customer-churn-interpretable": ProblemDefinition(
        slug="customer-churn-interpretable",
        title="Customer Churn with Explainability",
        task_type="classification",
        default_metric="f1",
        allowed_metrics=["f1"],
        submission_threshold=0.65,
        dataset_loader=_generic_classification_loader(1500, 12, 102),
        description="F1 >= 0.78 with SHAP explainability on telecom churn.",
        difficulty="medium",
        difficulty_rating=1200,
        category="business",
    ),
    "house-price-robust": ProblemDefinition(
        slug="house-price-robust",
        title="House Price — Robust Regression",
        task_type="regression",
        default_metric="rmse",
        allowed_metrics=["rmse"],
        submission_threshold=30.0,
        dataset_loader=_generic_regression_loader(400, 8, 103),
        description="Detect outliers and achieve RMSE <= 25000 on house prices.",
        difficulty="medium",
        difficulty_rating=1200,
        category="real_estate",
    ),
    "multi-label-classification": ProblemDefinition(
        slug="multi-label-classification",
        title="Multi-Label Text Topic Classification",
        task_type="classification",
        default_metric="f1",
        allowed_metrics=["f1"],
        submission_threshold=0.55,
        dataset_loader=_generic_classification_loader(800, 20, 104),
        description="Multi-label news tagging with Hamming Loss <= 0.12.",
        difficulty="medium",
        difficulty_rating=1200,
        category="nlp",
    ),
    "timeseries-features": ProblemDefinition(
        slug="timeseries-features",
        title="Time Series Feature Engineering",
        task_type="regression",
        default_metric="mae",
        allowed_metrics=["mae"],
        submission_threshold=50.0,
        dataset_loader=_generic_regression_loader(730, 15, 105),
        description="Engineer lag/rolling/calendar features. MAE <= 420.",
        difficulty="medium",
        difficulty_rating=1200,
        category="forecasting",
    ),
    "loan-default-pipeline": ProblemDefinition(
        slug="loan-default-pipeline",
        title="End-to-End ML Pipeline (Loan Default)",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy", "roc_auc"],
        submission_threshold=0.78,
        dataset_loader=_generic_classification_loader(3000, 15, 106),
        description="ColumnTransformer pipeline. AUC-ROC >= 0.88.",
        difficulty="medium",
        difficulty_rating=1200,
        category="finance",
    ),
    "recommender-matrix-factorisation": ProblemDefinition(
        slug="recommender-matrix-factorisation",
        title="Collaborative Filtering Recommender",
        task_type="regression",
        default_metric="rmse",
        allowed_metrics=["rmse"],
        submission_threshold=1.5,
        dataset_loader=_generic_regression_loader(500, 10, 107),
        description="SVD matrix factorisation from scratch. RMSE <= 0.95.",
        difficulty="medium",
        difficulty_rating=1200,
        category="recommendations",
    ),
    "ensemble-stacking": ProblemDefinition(
        slug="ensemble-stacking",
        title="Stacking Ensemble",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy", "roc_auc"],
        submission_threshold=0.82,
        dataset_loader=_generic_classification_loader(1000, 10, 108),
        description="Manual stacking ensemble. AUC >= 0.91.",
        difficulty="medium",
        difficulty_rating=1200,
        category="fundamentals",
    ),
    "anomaly-detection-unsupervised": ProblemDefinition(
        slug="anomaly-detection-unsupervised",
        title="Unsupervised Anomaly Detection",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy", "roc_auc"],
        submission_threshold=0.80,
        dataset_loader=_generic_classification_loader(800, 8, 109),
        description="Train on normal data only. AUC-ROC >= 0.88.",
        difficulty="medium",
        difficulty_rating=1200,
        category="manufacturing",
    ),
    "survival-analysis-churn": ProblemDefinition(
        slug="survival-analysis-churn",
        title="Survival Analysis for Customer Lifetime",
        task_type="regression",
        default_metric="rmse",
        allowed_metrics=["rmse"],
        submission_threshold=20.0,
        dataset_loader=_generic_regression_loader(1200, 8, 110),
        description="Cox PH model. C-index >= 0.75.",
        difficulty="medium",
        difficulty_rating=1200,
        category="business",
    ),
    # Hard (8 new)
    "gradient-descent-scratch": ProblemDefinition(
        slug="gradient-descent-scratch",
        title="Implement Gradient Descent from Scratch",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(500, 5, 201),
        description="Mini-batch SGD logistic regression from scratch. Loss <= 0.25.",
        difficulty="hard",
        difficulty_rating=1600,
        category="fundamentals",
    ),
    "kmeans-from-scratch": ProblemDefinition(
        slug="kmeans-from-scratch",
        title="K-Means Clustering from Scratch",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(300, 2, 202),
        description="KMeans++ from scratch. Inertia within 5% of sklearn.",
        difficulty="hard",
        difficulty_rating=1600,
        category="fundamentals",
    ),
    "decision-tree-scratch": ProblemDefinition(
        slug="decision-tree-scratch",
        title="Decision Tree from Scratch",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.80,
        dataset_loader=_generic_classification_loader(400, 4, 203),
        description="Decision tree with Gini/entropy. Accuracy >= 0.87.",
        difficulty="hard",
        difficulty_rating=1600,
        category="fundamentals",
    ),
    "backpropagation-scratch": ProblemDefinition(
        slug="backpropagation-scratch",
        title="Neural Network Backpropagation from Scratch",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.82,
        dataset_loader=_generic_classification_loader(500, 2, 204),
        description="2-layer NN with Adam from scratch. Accuracy >= 0.90.",
        difficulty="hard",
        difficulty_rating=1600,
        category="deep_learning",
    ),
    "pca-from-scratch": ProblemDefinition(
        slug="pca-from-scratch",
        title="PCA from Scratch + Reconstruction",
        task_type="regression",
        default_metric="rmse",
        allowed_metrics=["rmse"],
        submission_threshold=5.0,
        dataset_loader=_generic_regression_loader(300, 10, 205),
        description="PCA from scratch. Reconstruction error within 1e-10 of sklearn.",
        difficulty="hard",
        difficulty_rating=1600,
        category="unsupervised",
    ),
    "timeseries-lgbm-forecast": ProblemDefinition(
        slug="timeseries-lgbm-forecast",
        title="Multi-Step Time Series Forecasting",
        task_type="regression",
        default_metric="mae",
        allowed_metrics=["mae"],
        submission_threshold=100.0,
        dataset_loader=_generic_regression_loader(8760, 20, 206),
        description="LightGBM direct multi-step. MAPE <= 4.5%.",
        difficulty="hard",
        difficulty_rating=1600,
        category="forecasting",
    ),
    "bert-sentiment-finetuning": ProblemDefinition(
        slug="bert-sentiment-finetuning",
        title="BERT Fine-tuning for Sentiment",
        task_type="classification",
        default_metric="f1",
        allowed_metrics=["f1"],
        submission_threshold=0.70,
        dataset_loader=_generic_classification_loader(500, 15, 207),
        description="DistilBERT 3-class sentiment. Macro F1 >= 0.82.",
        difficulty="hard",
        difficulty_rating=1600,
        category="nlp",
    ),
    "feature-store-pipeline": ProblemDefinition(
        slug="feature-store-pipeline",
        title="Feature Store Pipeline",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(1000, 8, 208),
        description="FeatureStore with point-in-time correctness.",
        difficulty="hard",
        difficulty_rating=1600,
        category="mlops",
    ),
    "hyperparameter-optimisation": ProblemDefinition(
        slug="hyperparameter-optimisation",
        title="Bayesian Hyperparameter Optimisation",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy", "roc_auc"],
        submission_threshold=0.85,
        dataset_loader=_generic_classification_loader(1500, 10, 209),
        description="Optuna XGBoost tuning. AUC >= 0.935 in 50 trials.",
        difficulty="hard",
        difficulty_rating=1600,
        category="mlops",
    ),
    # Expert (9 new)
    "asymmetric-cost-loss": ProblemDefinition(
        slug="asymmetric-cost-loss",
        title="Custom Loss Function (Asymmetric Cost)",
        task_type="classification",
        default_metric="f1",
        allowed_metrics=["f1"],
        submission_threshold=0.65,
        dataset_loader=_generic_classification_loader(2000, 10, 301),
        description="XGBoost custom asymmetric loss. Total cost <= 1500.",
        difficulty="expert",
        difficulty_rating=2000,
        category="finance",
    ),
    "transformer-attention-scratch": ProblemDefinition(
        slug="transformer-attention-scratch",
        title="Transformer Self-Attention from Scratch",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.70,
        dataset_loader=_generic_classification_loader(200, 512, 302),
        description="Multi-head attention from scratch using numpy.",
        difficulty="expert",
        difficulty_rating=2000,
        category="deep_learning",
    ),
    "federated-learning-simulation": ProblemDefinition(
        slug="federated-learning-simulation",
        title="Federated Learning (FedAvg)",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(1000, 784, 303),
        description="FedAvg across 10 clients. Global accuracy >= 0.82.",
        difficulty="expert",
        difficulty_rating=2000,
        category="advanced",
    ),
    "online-learning-adaptive": ProblemDefinition(
        slug="online-learning-adaptive",
        title="Online Learning with Adaptive Drift Response",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.70,
        dataset_loader=_generic_classification_loader(5000, 8, 304),
        description="ADWIN drift detector. Cumulative regret <= 4200.",
        difficulty="expert",
        difficulty_rating=2000,
        category="advanced",
    ),
    "uplift-modelling": ProblemDefinition(
        slug="uplift-modelling",
        title="Causal ML: Uplift Modelling",
        task_type="classification",
        default_metric="f1",
        allowed_metrics=["f1"],
        submission_threshold=0.60,
        dataset_loader=_generic_classification_loader(3000, 12, 305),
        description="T/S/X-learners. Qini coefficient >= 0.28.",
        difficulty="expert",
        difficulty_rating=2000,
        category="business",
    ),
    "graph-neural-network": ProblemDefinition(
        slug="graph-neural-network",
        title="Graph Neural Network for Fraud Detection",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy", "roc_auc"],
        submission_threshold=0.85,
        dataset_loader=_generic_classification_loader(2000, 16, 306),
        description="2-layer GCN. AUC-ROC >= 0.91.",
        difficulty="expert",
        difficulty_rating=2000,
        category="finance",
    ),
    "neural-architecture-search": ProblemDefinition(
        slug="neural-architecture-search",
        title="Differentiable Neural Architecture Search (DARTS)",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.85,
        dataset_loader=_generic_classification_loader(5000, 3072, 307),
        description="Simplified DARTS. >= 92% on CIFAR-10 subset.",
        difficulty="expert",
        difficulty_rating=2000,
        category="deep_learning",
    ),
    "rl-contextual-bandit": ProblemDefinition(
        slug="rl-contextual-bandit",
        title="Contextual Bandit for Personalised Recommendations",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(10000, 5, 308),
        description="LinUCB contextual bandit. Efficiency >= 0.88.",
        difficulty="expert",
        difficulty_rating=2000,
        category="recommendations",
    ),
    "e2e-ml-system": ProblemDefinition(
        slug="e2e-ml-system",
        title="Production ML System: Design + Implement",
        task_type="classification",
        default_metric="accuracy",
        allowed_metrics=["accuracy"],
        submission_threshold=0.75,
        dataset_loader=_generic_classification_loader(5000, 20, 309),
        description="Complete ML system: features, two-tower, serving, monitoring.",
        difficulty="expert",
        difficulty_rating=2000,
        category="mlops",
    ),
}
