# Generated by Django 4.2.10 on 2026-06-06 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('next_lesson', 'Next Lesson'), ('revision', 'Revision'), ('prerequisite', 'Prerequisite'), ('quiz', 'Quiz'), ('coding_problem', 'Coding Problem'), ('project', 'Project')], max_length=30)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.IntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('rule_based', 'Rule Based'), ('content_based', 'Content Based'), ('collaborative', 'Collaborative Filtering'), ('ml_model', 'ML Model')], default='rule_based', max_length=30)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-generated_at'],
                'indexes': [models.Index(fields=['user', 'recommendation_type', 'is_dismissed'], name='recommendat_user_id_d3c002_idx')],
            },
        ),
    ]
